<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CarlosRodriguezListingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get Carlos Rodriguez's user ID
        $carlosId = DB::table('users')->where('email', 'carlos.farmer@agribid.com')->value('id');
        
        if (!$carlosId) {
            $this->command->error('Carlos Rodriguez not found in database.');
            return;
        }

        // Get category IDs
        $categories = DB::table('categories')->pluck('id', 'slug')->toArray();
        
        $now = Carbon::now();
        
        $listings = [
            // FRUITS
            [
                'user_id' => $carlosId,
                'category_id' => $categories['fruits'],
                'name' => 'Premium Carabao Mangoes',
                'type' => 'Fruit',
                'quantity' => '150',
                'unit' => 'kg',
                'starting_bid' => 12000,
                'current_bid' => 0,
                'buy_now_price' => 15000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Sweet and juicy Carabao mangoes from my farm. Perfect ripeness, organic grown without pesticides. Ideal for fresh eating or making dried mangoes.',
                'image_url' => 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(7),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['fruits'],
                'name' => 'Fresh Lakatan Bananas',
                'type' => 'Fruit',
                'quantity' => '200',
                'unit' => 'kg',
                'starting_bid' => 6000,
                'current_bid' => 0,
                'buy_now_price' => 8000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Premium quality Lakatan bananas, freshly harvested this morning. Natural sweetness, no chemicals used. Great for banana cue, turon, or fresh consumption.',
                'image_url' => 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['fruits'],
                'name' => 'Organic Papaya',
                'type' => 'Fruit',
                'quantity' => '100',
                'unit' => 'kg',
                'starting_bid' => 5000,
                'current_bid' => 0,
                'buy_now_price' => 7000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Ripe and sweet papayas, rich in vitamins and enzymes. Perfect for breakfast, smoothies, or desserts. Organically grown.',
                'image_url' => 'https://images.unsplash.com/photo-1617112848923-cc2234396a8d?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['fruits'],
                'name' => 'Pineapple Premium',
                'type' => 'Fruit',
                'quantity' => '80',
                'unit' => 'pieces',
                'starting_bid' => 4000,
                'current_bid' => 0,
                'buy_now_price' => 5500,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Sweet Queen pineapples. Perfect for juice, desserts, or fresh eating. Each weighs approximately 1.5-2kg.',
                'image_url' => 'https://images.unsplash.com/photo-1587049352846-4a222e784210?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(6),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['fruits'],
                'name' => 'Calamansi Fresh',
                'type' => 'Fruit',
                'quantity' => '50',
                'unit' => 'kg',
                'starting_bid' => 3000,
                'current_bid' => 0,
                'buy_now_price' => 4000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh calamansi, perfect for cooking, beverages, and traditional Filipino dishes. High in Vitamin C.',
                'image_url' => 'https://images.unsplash.com/photo-1582281298055-e25b95a2c2f6?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],

            // VEGETABLES
            [
                'user_id' => $carlosId,
                'category_id' => $categories['vegetables'],
                'name' => 'Fresh Tomatoes',
                'type' => 'Vegetable',
                'quantity' => '120',
                'unit' => 'kg',
                'starting_bid' => 5000,
                'current_bid' => 0,
                'buy_now_price' => 7000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Ripe and juicy tomatoes, perfect for sauces, salads, and Filipino dishes. Freshly picked this morning.',
                'image_url' => 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['vegetables'],
                'name' => 'Eggplant Bundle',
                'type' => 'Vegetable',
                'quantity' => '80',
                'unit' => 'kg',
                'starting_bid' => 3500,
                'current_bid' => 0,
                'buy_now_price' => 5000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh eggplants, perfect for tortang talong, pinakbet, and other Filipino dishes. Grade A quality.',
                'image_url' => 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['vegetables'],
                'name' => 'Sitaw (String Beans)',
                'type' => 'Vegetable',
                'quantity' => '60',
                'unit' => 'kg',
                'starting_bid' => 2800,
                'current_bid' => 0,
                'buy_now_price' => 4000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh sitaw perfect for adobo, sinigang, and pinakbet. Crisp and tender.',
                'image_url' => 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['vegetables'],
                'name' => 'Ampalaya (Bitter Gourd)',
                'type' => 'Vegetable',
                'quantity' => '40',
                'unit' => 'kg',
                'starting_bid' => 3000,
                'current_bid' => 0,
                'buy_now_price' => 4500,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh ampalaya, excellent for health. Perfect for ginisang ampalaya or ampalaya salad.',
                'image_url' => 'https://images.unsplash.com/photo-1608617743175-decb74dc2ab2?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['vegetables'],
                'name' => 'Okra Fresh',
                'type' => 'Vegetable',
                'quantity' => '35',
                'unit' => 'kg',
                'starting_bid' => 2500,
                'current_bid' => 0,
                'buy_now_price' => 3500,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh okra, great for sinigang, pinakbet, and other vegetable dishes. Young and tender.',
                'image_url' => 'https://images.unsplash.com/photo-1610639028138-e6e53b23ee2f?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],

            // GRAINS & ROOT CROPS
            [
                'user_id' => $carlosId,
                'category_id' => $categories['grains'],
                'name' => 'Premium White Rice',
                'type' => 'Grain',
                'quantity' => '500',
                'unit' => 'kg',
                'starting_bid' => 28000,
                'current_bid' => 0,
                'buy_now_price' => 35000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Premium quality white rice from our paddy fields. Freshly milled, clean, and aromatic. Perfect for daily consumption.',
                'image_url' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(10),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['grains'],
                'name' => 'Sweet Corn Harvest',
                'type' => 'Grain',
                'quantity' => '200',
                'unit' => 'kg',
                'starting_bid' => 10000,
                'current_bid' => 0,
                'buy_now_price' => 13000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh yellow corn, sweet and tender. Perfect for boiling, grilling, or making corn soup.',
                'image_url' => 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['vegetables'],
                'name' => 'Sweet Potatoes (Kamote)',
                'type' => 'Root Crop',
                'quantity' => '100',
                'unit' => 'kg',
                'starting_bid' => 4000,
                'current_bid' => 0,
                'buy_now_price' => 6000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh sweet potatoes, rich in vitamins and fiber. Perfect for kamote cue, boiled, or baked.',
                'image_url' => 'https://images.unsplash.com/photo-1589927986089-35812378d4be?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(7),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],

            // HERBS & SPICES
            [
                'user_id' => $carlosId,
                'category_id' => $categories['herbs'],
                'name' => 'Fresh Ginger',
                'type' => 'Herb',
                'quantity' => '30',
                'unit' => 'kg',
                'starting_bid' => 3500,
                'current_bid' => 0,
                'buy_now_price' => 5000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh ginger roots, aromatic and spicy. Perfect for Filipino dishes, tea, and natural remedies.',
                'image_url' => 'https://images.unsplash.com/photo-1599909533166-e0a4e8bb7e4b?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(6),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'direct_buy',
            ],
            [
                'user_id' => $carlosId,
                'category_id' => $categories['herbs'],
                'name' => 'Lemongrass (Tanglad)',
                'type' => 'Herb',
                'quantity' => '20',
                'unit' => 'kg',
                'starting_bid' => 2000,
                'current_bid' => 0,
                'buy_now_price' => 3000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh lemongrass stalks, perfect for tea, soups, and Filipino dishes. Aromatic and medicinal.',
                'image_url' => 'https://images.unsplash.com/photo-1609159006463-9f8f7d09c3f1?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
                'listing_type' => 'auction',
            ],
        ];

        foreach ($listings as $listing) {
            DB::table('listings')->insert(array_merge($listing, [
                'sold_count' => rand(10, 85),
                'rating' => number_format(rand(40, 50) / 10, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        $this->command->info('Successfully created ' . count($listings) . ' listings for Carlos Rodriguez!');
    }
}
