<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('categories')->pluck('id', 'slug')->toArray();
        
        // Get farmer user IDs (users with role 'farmer')
        $farmers = DB::table('users')->where('role', 'farmer')->pluck('id')->toArray();
        
        if (empty($farmers)) {
            $this->command->error('No farmers found. Please run DatabaseSeeder first.');
            return;
        }

        $now = Carbon::now();
        $products = [
            // FRUITS (20 products)
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Fresh Bananas',
                'type' => 'Fruit',
                'quantity' => '100',
                'unit' => 'kg',
                'starting_bid' => 5000,
                'current_bid' => 0,
                'buy_now_price' => 7000,
                'location' => 'Anilao, Oriental Mindoro',
                'description' => 'Premium quality Lakatan bananas, freshly harvested',
                'image_url' => 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(7),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Organic Mangoes',
                'type' => 'Fruit',
                'quantity' => '75',
                'unit' => 'kg',
                'starting_bid' => 8000,
                'current_bid' => 0,
                'buy_now_price' => 10000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Sweet and juicy Carabao mangoes, organic certified',
                'image_url' => 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Pineapple Bundle',
                'type' => 'Fruit',
                'quantity' => '50',
                'unit' => 'pieces',
                'starting_bid' => 3000,
                'current_bid' => 0,
                'buy_now_price' => 4000,
                'location' => 'Bongabong, Oriental Mindoro',
                'description' => 'Fresh Queen pineapples, perfect for juice and desserts',
                'image_url' => 'https://images.unsplash.com/photo-1587049352846-4a222e784210?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(6),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Papaya Harvest',
                'type' => 'Fruit',
                'quantity' => '80',
                'unit' => 'kg',
                'starting_bid' => 4500,
                'current_bid' => 0,
                'buy_now_price' => 6000,
                'location' => 'Roxas, Oriental Mindoro',
                'description' => 'Ripe and sweet papayas, rich in vitamins',
                'image_url' => 'https://images.unsplash.com/photo-1617112848923-cc2234396a8d?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Premium Avocados',
                'type' => 'Fruit',
                'quantity' => '40',
                'unit' => 'kg',
                'starting_bid' => 12000,
                'current_bid' => 0,
                'buy_now_price' => 15000,
                'location' => 'Naujan, Oriental Mindoro',
                'description' => 'Creamy avocados, perfect for salads and smoothies',
                'image_url' => 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Watermelon Bundle',
                'type' => 'Fruit',
                'quantity' => '30',
                'unit' => 'pieces',
                'starting_bid' => 6000,
                'current_bid' => 0,
                'buy_now_price' => 8000,
                'location' => 'Victoria, Oriental Mindoro',
                'description' => 'Large, sweet watermelons perfect for summer',
                'image_url' => 'https://images.unsplash.com/photo-1582281298055-e25b95a2c2f6?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Fresh Oranges',
                'type' => 'Fruit',
                'quantity' => '60',
                'unit' => 'kg',
                'starting_bid' => 7000,
                'current_bid' => 0,
                'buy_now_price' => 9000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Juicy oranges loaded with Vitamin C',
                'image_url' => 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(6),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['fruits'],
                'name' => 'Dragon Fruit',
                'type' => 'Fruit',
                'quantity' => '25',
                'unit' => 'kg',
                'starting_bid' => 10000,
                'current_bid' => 0,
                'buy_now_price' => 12000,
                'location' => 'Bongabong, Oriental Mindoro',
                'description' => 'Exotic dragon fruit, rich in antioxidants',
                'image_url' => 'https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
            ],

            // VEGETABLES (20 products)
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Fresh Tomatoes',
                'type' => 'Vegetable',
                'quantity' => '120',
                'unit' => 'kg',
                'starting_bid' => 4000,
                'current_bid' => 0,
                'buy_now_price' => 5500,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Ripe and juicy tomatoes, perfect for cooking',
                'image_url' => 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Organic Lettuce',
                'type' => 'Vegetable',
                'quantity' => '40',
                'unit' => 'kg',
                'starting_bid' => 3500,
                'current_bid' => 0,
                'buy_now_price' => 5000,
                'location' => 'Naujan, Oriental Mindoro',
                'description' => 'Crisp organic lettuce, pesticide-free',
                'image_url' => 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Eggplant Bundle',
                'type' => 'Vegetable',
                'quantity' => '70',
                'unit' => 'kg',
                'starting_bid' => 3000,
                'current_bid' => 0,
                'buy_now_price' => 4000,
                'location' => 'Bongabong, Oriental Mindoro',
                'description' => 'Fresh eggplants, perfect for Filipino dishes',
                'image_url' => 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Carrots Harvest',
                'type' => 'Vegetable',
                'quantity' => '90',
                'unit' => 'kg',
                'starting_bid' => 4500,
                'current_bid' => 0,
                'buy_now_price' => 6000,
                'location' => 'Victoria, Oriental Mindoro',
                'description' => 'Sweet and crunchy carrots, high in beta-carotene',
                'image_url' => 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(6),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Bell Peppers Mix',
                'type' => 'Vegetable',
                'quantity' => '50',
                'unit' => 'kg',
                'starting_bid' => 6000,
                'current_bid' => 0,
                'buy_now_price' => 8000,
                'location' => 'Roxas, Oriental Mindoro',
                'description' => 'Colorful bell peppers - red, yellow, green',
                'image_url' => 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(5),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Cabbage Bundle',
                'type' => 'Vegetable',
                'quantity' => '100',
                'unit' => 'kg',
                'starting_bid' => 3500,
                'current_bid' => 0,
                'buy_now_price' => 5000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Fresh green cabbage, perfect for salads',
                'image_url' => 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Potato Sack',
                'type' => 'Vegetable',
                'quantity' => '150',
                'unit' => 'kg',
                'starting_bid' => 5000,
                'current_bid' => 0,
                'buy_now_price' => 7000,
                'location' => 'Naujan, Oriental Mindoro',
                'description' => 'Fresh potatoes, ideal for various dishes',
                'image_url' => 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(7),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['vegetables'],
                'name' => 'Okra Fresh',
                'type' => 'Vegetable',
                'quantity' => '30',
                'unit' => 'kg',
                'starting_bid' => 2500,
                'current_bid' => 0,
                'buy_now_price' => 3500,
                'location' => 'Bongabong, Oriental Mindoro',
                'description' => 'Fresh okra, great for sinigang and pinakbet',
                'image_url' => 'https://images.unsplash.com/photo-1610639028138-e6e53b23ee2f?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],

            // GRAINS (15 products)
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['grains'],
                'name' => 'Rice Harvest',
                'type' => 'Grain',
                'quantity' => '500',
                'unit' => 'kg',
                'starting_bid' => 25000,
                'current_bid' => 0,
                'buy_now_price' => 30000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Premium quality white rice, freshly milled',
                'image_url' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(10),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['grains'],
                'name' => 'Corn Harvest',
                'type' => 'Grain',
                'quantity' => '300',
                'unit' => 'kg',
                'starting_bid' => 15000,
                'current_bid' => 0,
                'buy_now_price' => 18000,
                'location' => 'Victoria, Oriental Mindoro',
                'description' => 'Fresh yellow corn, sweet and tender',
                'image_url' => 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(8),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['grains'],
                'name' => 'Brown Rice',
                'type' => 'Grain',
                'quantity' => '200',
                'unit' => 'kg',
                'starting_bid' => 18000,
                'current_bid' => 0,
                'buy_now_price' => 22000,
                'location' => 'Naujan, Oriental Mindoro',
                'description' => 'Healthy brown rice, rich in fiber',
                'image_url' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(9),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['grains'],
                'name' => 'Wheat Bundle',
                'type' => 'Grain',
                'quantity' => '250',
                'unit' => 'kg',
                'starting_bid' => 12000,
                'current_bid' => 0,
                'buy_now_price' => 15000,
                'location' => 'Roxas, Oriental Mindoro',
                'description' => 'Quality wheat grains for milling',
                'image_url' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(7),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['grains'],
                'name' => 'Oats Premium',
                'type' => 'Grain',
                'quantity' => '100',
                'unit' => 'kg',
                'starting_bid' => 10000,
                'current_bid' => 0,
                'buy_now_price' => 13000,
                'location' => 'Bongabong, Oriental Mindoro',
                'description' => 'Rolled oats, perfect for breakfast',
                'image_url' => 'https://images.unsplash.com/photo-1517098970177-3c76d5a36d4e?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(6),
                'status' => 'active',
                'approval_status' => 'approved',
            ],

            // HERBS (10 products)
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['herbs'],
                'name' => 'Fresh Basil',
                'type' => 'Herb',
                'quantity' => '10',
                'unit' => 'kg',
                'starting_bid' => 2000,
                'current_bid' => 0,
                'buy_now_price' => 2500,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Aromatic basil leaves, perfect for Italian dishes',
                'image_url' => 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(2),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['herbs'],
                'name' => 'Mint Leaves',
                'type' => 'Herb',
                'quantity' => '8',
                'unit' => 'kg',
                'starting_bid' => 1800,
                'current_bid' => 0,
                'buy_now_price' => 2300,
                'location' => 'Naujan, Oriental Mindoro',
                'description' => 'Fresh mint for beverages and desserts',
                'image_url' => 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(2),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['herbs'],
                'name' => 'Oregano Bundle',
                'type' => 'Herb',
                'quantity' => '5',
                'unit' => 'kg',
                'starting_bid' => 1500,
                'current_bid' => 0,
                'buy_now_price' => 2000,
                'location' => 'Victoria, Oriental Mindoro',
                'description' => 'Dried oregano for seasoning',
                'image_url' => 'https://images.unsplash.com/photo-1584278952610-b7a5f0a7f321?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['herbs'],
                'name' => 'Rosemary Fresh',
                'type' => 'Herb',
                'quantity' => '6',
                'unit' => 'kg',
                'starting_bid' => 1700,
                'current_bid' => 0,
                'buy_now_price' => 2200,
                'location' => 'Roxas, Oriental Mindoro',
                'description' => 'Fragrant rosemary for cooking',
                'image_url' => 'https://images.unsplash.com/photo-1595910747748-0668b9e8e5c7?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(2),
                'status' => 'active',
                'approval_status' => 'approved',
            ],

            // DAIRY (8 products)
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['dairy'],
                'name' => 'Fresh Milk',
                'type' => 'Dairy',
                'quantity' => '50',
                'unit' => 'lbs',
                'starting_bid' => 8000,
                'current_bid' => 0,
                'buy_now_price' => 10000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Pure cow\'s milk, daily fresh',
                'image_url' => 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(1),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['dairy'],
                'name' => 'Cheese Blocks',
                'type' => 'Dairy',
                'quantity' => '20',
                'unit' => 'kg',
                'starting_bid' => 12000,
                'current_bid' => 0,
                'buy_now_price' => 15000,
                'location' => 'Naujan, Oriental Mindoro',
                'description' => 'Homemade cheese, various flavors',
                'image_url' => 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['dairy'],
                'name' => 'Butter Fresh',
                'type' => 'Dairy',
                'quantity' => '15',
                'unit' => 'kg',
                'starting_bid' => 9000,
                'current_bid' => 0,
                'buy_now_price' => 11000,
                'location' => 'Victoria, Oriental Mindoro',
                'description' => 'Farm-made butter, creamy and rich',
                'image_url' => 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(2),
                'status' => 'active',
                'approval_status' => 'approved',
            ],

            // POULTRY (10 products)
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['poultry'],
                'name' => 'Free Range Eggs',
                'type' => 'Poultry',
                'quantity' => '200',
                'unit' => 'pieces',
                'starting_bid' => 3000,
                'current_bid' => 0,
                'buy_now_price' => 4000,
                'location' => 'Calapan City, Oriental Mindoro',
                'description' => 'Farm fresh eggs from free-range chickens',
                'image_url' => 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['poultry'],
                'name' => 'Live Chickens',
                'type' => 'Poultry',
                'quantity' => '20',
                'unit' => 'pieces',
                'starting_bid' => 8000,
                'current_bid' => 0,
                'buy_now_price' => 10000,
                'location' => 'Bongabong, Oriental Mindoro',
                'description' => 'Healthy native chickens, 1.5-2kg each',
                'image_url' => 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(4),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'user_id' => $farmers[array_rand($farmers)],
                'category_id' => $categories['poultry'],
                'name' => 'Duck Eggs',
                'type' => 'Poultry',
                'quantity' => '100',
                'unit' => 'pieces',
                'starting_bid' => 2000,
                'current_bid' => 0,
                'buy_now_price' => 2800,
                'location' => 'Roxas, Oriental Mindoro',
                'description' => 'Fresh duck eggs, great for baking',
                'image_url' => 'https://images.unsplash.com/photo-1569288052389-dac9b01c0f17?w=400&h=300&fit=crop',
                'auction_start' => $now,
                'auction_end' => $now->copy()->addDays(3),
                'status' => 'active',
                'approval_status' => 'approved',
            ],
        ];

        foreach ($products as $product) {
            DB::table('listings')->insert(array_merge($product, [
                'sold_count' => rand(15, 150),
                'rating' => number_format(rand(35, 50) / 10, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        $this->command->info('Successfully seeded ' . count($products) . ' products!');
    }
}
