<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('categories')->pluck('id', 'slug')->toArray();
        
        // Get farmer user ID (assuming user_id 1 is John Farmer)
        $farmerId = 1;
        
        $now = now();
        
        $listings = [
            // FRUITS (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Cavendish Bananas', 'description' => 'Premium quality Cavendish bananas, freshly harvested. Perfect for daily consumption, desserts, and smoothies.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '500', 'unit' => 'kg', 'buy_now_price' => 45.00, 'location' => 'Davao City, Philippines', 'harvest_date' => Carbon::now()->subDays(2)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Fresh Mangoes', 'description' => 'Sweet and juicy Philippine mangoes. Handpicked at peak ripeness for maximum sweetness and flavor.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '200', 'unit' => 'kg', 'starting_bid' => 80.00, 'current_bid' => 80.00, 'buy_now_price' => 120.00, 'location' => 'Guimaras, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(10)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Pineapple', 'description' => 'Fresh Queen pineapples with sweet and tangy flavor. Excellent for juicing and fresh consumption.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '300', 'unit' => 'pieces', 'buy_now_price' => 35.00, 'location' => 'Bukidnon, Philippines', 'harvest_date' => Carbon::now()->subDays(3)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(14)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1550828520-4cb496926fc9?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Papaya', 'description' => 'Ripe and sweet papaya fruits, rich in vitamins and antioxidants. Great for breakfast and smoothies.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '150', 'unit' => 'kg', 'buy_now_price' => 38.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Watermelon', 'description' => 'Sweet and juicy watermelons perfect for hot summer days. Fresh from the farm.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '250', 'unit' => 'kg', 'starting_bid' => 25.00, 'current_bid' => 25.00, 'buy_now_price' => 40.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->subDays(2)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(10)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(4), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Oranges', 'description' => 'Fresh and tangy oranges packed with vitamin C. Perfect for juice and snacking.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '180', 'unit' => 'kg', 'buy_now_price' => 65.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(14)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Dragon Fruit', 'description' => 'Exotic dragon fruit with stunning pink flesh. Rich in antioxidants and fiber.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '100', 'unit' => 'kg', 'starting_bid' => 90.00, 'current_bid' => 90.00, 'buy_now_price' => 130.00, 'location' => 'Iloilo, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(1), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Pomelo', 'description' => 'Large sweet pomelos with thick rind and juicy segments. Rich in vitamin C.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '120', 'unit' => 'kg', 'buy_now_price' => 58.00, 'location' => 'Davao, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(21)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Guava', 'description' => 'Fresh guavas with sweet tropical flavor. High in fiber and vitamin C.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '90', 'unit' => 'kg', 'buy_now_price' => 42.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['fruits'] ?? 2, 'name' => 'Lanzones', 'description' => 'Sweet and tangy lanzones fruit, a Filipino favorite. Fresh harvest from Camiguin.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '80', 'unit' => 'kg', 'starting_bid' => 55.00, 'current_bid' => 55.00, 'buy_now_price' => 75.00, 'location' => 'Camiguin, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subMinutes(30), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1589927986089-35812388d1f8?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            
            // VEGETABLES (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Fresh Organic Lettuce', 'description' => 'Crisp and fresh organic lettuce, perfect for salads. Grown without pesticides using organic farming methods.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '100', 'unit' => 'kg', 'buy_now_price' => 85.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Roma Tomatoes', 'description' => 'Fresh Roma tomatoes, perfect for cooking and salads. Firm texture and rich flavor.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '150', 'unit' => 'kg', 'starting_bid' => 40.00, 'current_bid' => 40.00, 'buy_now_price' => 65.00, 'location' => 'Nueva Ecija, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(5), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1546470427-227a8e03f4f4?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Fresh Carrots', 'description' => 'Crunchy and sweet carrots, rich in vitamins. Perfect for cooking, juicing, or eating raw.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '200', 'unit' => 'kg', 'buy_now_price' => 55.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->subDays(2)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(30)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Cabbage', 'description' => 'Fresh green cabbage heads, perfect for coleslaw and stir-fry dishes. Crisp and tender.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '200', 'unit' => 'kg', 'buy_now_price' => 32.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(21)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Eggplant', 'description' => 'Fresh purple eggplants ideal for Filipino dishes. Tender and flavorful.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '130', 'unit' => 'kg', 'starting_bid' => 35.00, 'current_bid' => 35.00, 'buy_now_price' => 50.00, 'location' => 'Nueva Ecija, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1659261200833-ec993e501242?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Bell Peppers', 'description' => 'Colorful bell peppers (red, yellow, green) rich in vitamins. Perfect for salads and stir-fry.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '80', 'unit' => 'kg', 'buy_now_price' => 95.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(10)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Red Onions', 'description' => 'Fresh red onions with strong flavor. Essential ingredient for Filipino cooking.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '250', 'unit' => 'kg', 'buy_now_price' => 48.00, 'location' => 'Nueva Ecija, Philippines', 'harvest_date' => Carbon::now()->subDays(3)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(30)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Native Garlic', 'description' => 'Strong and aromatic native garlic bulbs. Premium quality for cooking.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '100', 'unit' => 'kg', 'starting_bid' => 70.00, 'current_bid' => 70.00, 'buy_now_price' => 95.00, 'location' => 'Ilocos Norte, Philippines', 'harvest_date' => Carbon::now()->subDays(5)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(45)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(5), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1583196443844-f8c7c6b51e1b?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Squash', 'description' => 'Fresh kalabasa (squash) perfect for Filipino dishes like ginataang kalabasa.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '180', 'unit' => 'kg', 'buy_now_price' => 28.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->subDays(2)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(30)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1570268999668-50b63dd88d86?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['vegetables'] ?? 1, 'name' => 'Bitter Gourd (Ampalaya)', 'description' => 'Fresh bitter gourd, rich in nutrients and perfect for traditional Filipino recipes.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '90', 'unit' => 'kg', 'buy_now_price' => 52.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            
            // GRAINS (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Premium White Rice', 'description' => 'High-quality milled white rice. Perfect for daily meals. Properly dried and cleaned.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '1000', 'unit' => 'kg', 'buy_now_price' => 42.00, 'location' => 'Nueva Ecija, Philippines', 'harvest_date' => Carbon::now()->subDays(30)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Yellow Corn', 'description' => 'Fresh yellow corn kernels, perfect for animal feed or human consumption. High nutritional value.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '500', 'unit' => 'kg', 'starting_bid' => 25.00, 'current_bid' => 25.00, 'buy_now_price' => 40.00, 'location' => 'Isabela, Philippines', 'harvest_date' => Carbon::now()->subDays(10)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(180)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(3), 'auction_end' => Carbon::now()->addDays(4), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Brown Rice', 'description' => 'Organic whole grain brown rice with natural bran layer. Higher fiber and nutrients than white rice.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '800', 'unit' => 'kg', 'buy_now_price' => 58.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->subDays(25)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Wheat Grains', 'description' => 'High-quality wheat grains suitable for milling into flour. Perfect for bread and pastries.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '600', 'unit' => 'kg', 'starting_bid' => 38.00, 'current_bid' => 38.00, 'buy_now_price' => 55.00, 'location' => 'Pangasinan, Philippines', 'harvest_date' => Carbon::now()->subDays(20)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(6), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Oats', 'description' => 'Whole grain oats perfect for breakfast porridge. High in fiber and protein.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '400', 'unit' => 'kg', 'buy_now_price' => 75.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->subDays(15)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1574110906667-909a6408e9b0?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Barley', 'description' => 'Premium barley grains for soups and beverages. Rich in fiber and minerals.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '350', 'unit' => 'kg', 'buy_now_price' => 65.00, 'location' => 'Mountain Province, Philippines', 'harvest_date' => Carbon::now()->subDays(12)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1595855759920-86ebfd3fff1f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Sorghum', 'description' => 'Gluten-free sorghum grains, excellent alternative to wheat. Nutritious and versatile.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '300', 'unit' => 'kg', 'starting_bid' => 45.00, 'current_bid' => 45.00, 'buy_now_price' => 68.00, 'location' => 'Isabela, Philippines', 'harvest_date' => Carbon::now()->subDays(18)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(4), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1569166801816-eb57e72c636c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Millet', 'description' => 'Nutritious millet grains high in protein and minerals. Perfect for health-conscious consumers.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '280', 'unit' => 'kg', 'buy_now_price' => 72.00, 'location' => 'Cagayan, Philippines', 'harvest_date' => Carbon::now()->subDays(22)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1602313642657-ffc8c7c65b4f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Quinoa', 'description' => 'Premium quinoa seeds, superfood with complete protein. Imported variety, locally grown.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '200', 'unit' => 'kg', 'starting_bid' => 120.00, 'current_bid' => 120.00, 'buy_now_price' => 165.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->subDays(10)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(4), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['grains'] ?? 3, 'name' => 'Buckwheat', 'description' => 'Gluten-free buckwheat groats, excellent for noodles and porridge. High in fiber.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '250', 'unit' => 'kg', 'buy_now_price' => 88.00, 'location' => 'Ifugao, Philippines', 'harvest_date' => Carbon::now()->subDays(14)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1593377441744-9b0c59c2b19c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            
            // HERBS (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Fresh Basil', 'description' => 'Aromatic fresh basil leaves, perfect for Italian dishes, pesto, and garnishes. Organically grown.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '20', 'unit' => 'kg', 'buy_now_price' => 150.00, 'location' => 'Tagaytay, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(3)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Lemongrass', 'description' => 'Fresh lemongrass stalks with citrusy aroma. Great for teas, soups, and Asian cuisine.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '50', 'unit' => 'kg', 'buy_now_price' => 95.00, 'location' => 'Quezon Province, Philippines', 'harvest_date' => Carbon::now()->subDays(1)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(14)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1596547609652-e8f0f9ad2b2b?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Fresh Mint', 'description' => 'Cool and refreshing mint leaves, perfect for teas, cocktails, and desserts.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '15', 'unit' => 'kg', 'buy_now_price' => 135.00, 'location' => 'Baguio City, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Oregano', 'description' => 'Dried oregano leaves with intense flavor. Essential for Italian and Mediterranean cooking.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '25', 'unit' => 'kg', 'starting_bid' => 180.00, 'current_bid' => 180.00, 'buy_now_price' => 240.00, 'location' => 'Tagaytay, Philippines', 'harvest_date' => Carbon::now()->subDays(5)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(180)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(3), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1608598793226-3f42fbfce764?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Rosemary', 'description' => 'Fresh rosemary sprigs with pine-like aroma. Perfect for roasted meats and potatoes.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '18', 'unit' => 'kg', 'buy_now_price' => 165.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(10)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1583116646097-91c81e825c5c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Thyme', 'description' => 'Fresh thyme leaves with earthy flavor. Versatile herb for soups, stews, and marinades.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '12', 'unit' => 'kg', 'buy_now_price' => 145.00, 'location' => 'Tagaytay, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1590855159-1f9c74a2d56f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Parsley', 'description' => 'Fresh curly parsley, perfect for garnishing and adding flavor to dishes.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '22', 'unit' => 'kg', 'starting_bid' => 110.00, 'current_bid' => 110.00, 'buy_now_price' => 155.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1557498173-7aa961ea3fda?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Cilantro (Wansoy)', 'description' => 'Fresh cilantro leaves with distinctive flavor. Popular in Filipino and Asian cooking.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '16', 'unit' => 'kg', 'buy_now_price' => 125.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(4)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Dill', 'description' => 'Fresh dill with feathery leaves and mild flavor. Great for fish dishes and pickling.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '10', 'unit' => 'kg', 'buy_now_price' => 155.00, 'location' => 'Tagaytay, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1607426919755-9f5a6c8c7db3?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['herbs'] ?? 5, 'name' => 'Sage', 'description' => 'Fresh sage leaves with pungent, earthy flavor. Perfect for poultry and pasta dishes.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '14', 'unit' => 'kg', 'starting_bid' => 140.00, 'current_bid' => 140.00, 'buy_now_price' => 190.00, 'location' => 'Benguet, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(1), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1598210223970-37e6f1e0e820?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            
            // DAIRY (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Fresh Carabao Milk', 'description' => 'Pure and fresh carabao milk, rich in nutrients and creamier than cow milk. Pasteurized and safe.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '100', 'unit' => 'liters', 'buy_now_price' => 120.00, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(3)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Fresh Cow Milk', 'description' => 'Farm-fresh cow milk, pasteurized daily. Rich in calcium and protein.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '200', 'unit' => 'liters', 'buy_now_price' => 85.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(5)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Goat Milk', 'description' => 'Fresh goat milk, easier to digest than cow milk. Rich in nutrients and minerals.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '80', 'unit' => 'liters', 'starting_bid' => 105.00, 'current_bid' => 105.00, 'buy_now_price' => 145.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(4)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(1), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'White Cheese (Kesong Puti)', 'description' => 'Traditional Filipino white cheese made from carabao milk. Fresh and soft texture.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '50', 'unit' => 'kg', 'buy_now_price' => 280.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Natural Yogurt', 'description' => 'Homemade natural yogurt with live cultures. No artificial flavors or sweeteners.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '60', 'unit' => 'liters', 'buy_now_price' => 95.00, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(10)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Farm Butter', 'description' => 'Artisan butter churned from fresh cream. Rich flavor and natural golden color.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '40', 'unit' => 'kg', 'starting_bid' => 320.00, 'current_bid' => 320.00, 'buy_now_price' => 420.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(30)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(4), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Fresh Cream', 'description' => 'Heavy cream perfect for cooking and baking. High fat content for rich recipes.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '45', 'unit' => 'liters', 'buy_now_price' => 185.00, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(7)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1628187658632-5e8d141d36dd?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Kefir', 'description' => 'Probiotic-rich kefir drink made from milk. Great for digestive health.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '35', 'unit' => 'liters', 'buy_now_price' => 115.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(14)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Cottage Cheese', 'description' => 'Fresh cottage cheese with mild flavor. High in protein and low in fat.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '30', 'unit' => 'kg', 'starting_bid' => 165.00, 'current_bid' => 165.00, 'buy_now_price' => 215.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(10)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(3), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['dairy'] ?? 6, 'name' => 'Sour Cream', 'description' => 'Tangy sour cream perfect for dips and toppings. Made from fresh cream.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '25', 'unit' => 'liters', 'buy_now_price' => 145.00, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(14)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            
            // POULTRY (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Farm Fresh Eggs', 'description' => 'Free-range chicken eggs from healthy hens. Rich in protein and nutrients. Daily fresh collection.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '500', 'unit' => 'pieces', 'buy_now_price' => 7.50, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(21)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Native Chicken', 'description' => 'Healthy native chickens raised in free-range conditions. Excellent meat quality and flavor.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '50', 'unit' => 'pieces', 'starting_bid' => 200.00, 'current_bid' => 200.00, 'buy_now_price' => 280.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(1)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(1), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Duck Eggs', 'description' => 'Large duck eggs with rich flavor. Perfect for salted eggs or baking.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '300', 'unit' => 'pieces', 'buy_now_price' => 9.50, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(21)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1587486937738-7ef75109fcf1?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Quail Eggs', 'description' => 'Fresh quail eggs, high in protein and minerals. Perfect for appetizers and salads.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '600', 'unit' => 'pieces', 'starting_bid' => 3.50, 'current_bid' => 3.50, 'buy_now_price' => 5.00, 'location' => 'Rizal, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(14)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1522617644329-14e8a7c24c31?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Broiler Chicken', 'description' => 'Tender broiler chickens, ready for cooking. Raised with quality feed.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '80', 'unit' => 'kg', 'buy_now_price' => 145.00, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(2)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Free-Range Chicken', 'description' => 'Premium free-range chickens with better flavor and texture. Ethically raised.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '40', 'unit' => 'kg', 'starting_bid' => 220.00, 'current_bid' => 220.00, 'buy_now_price' => 300.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(2)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(3), 'auction_end' => Carbon::now()->addDays(1), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Duck Meat', 'description' => 'Fresh duck meat with rich flavor. Perfect for traditional Filipino dishes.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '35', 'unit' => 'kg', 'buy_now_price' => 185.00, 'location' => 'Pampanga, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(2)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1588953936179-d2a4734c5490?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Turkey', 'description' => 'Whole turkey, perfect for special occasions and celebrations. Lean and healthy meat.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '20', 'unit' => 'kg', 'starting_bid' => 280.00, 'current_bid' => 280.00, 'buy_now_price' => 380.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(3)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(1), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1551881192-66f3e6e047ca?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Quail Meat', 'description' => 'Delicate quail meat, considered a delicacy. Perfect for gourmet dishes.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '25', 'unit' => 'kg', 'buy_now_price' => 320.00, 'location' => 'Rizal, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(2)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['poultry'] ?? 7, 'name' => 'Chicken Liver', 'description' => 'Fresh chicken liver, rich in iron and vitamins. Perfect for various Filipino dishes.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '30', 'unit' => 'kg', 'buy_now_price' => 95.00, 'location' => 'Bulacan, Philippines', 'harvest_date' => Carbon::now()->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(1)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            
            // FARM INPUTS (10+ products)
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Organic Fertilizer', 'description' => 'Premium organic fertilizer made from composted materials. Perfect for all crops. NPK balanced formula.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '1000', 'unit' => 'kg', 'buy_now_price' => 25.00, 'location' => 'Pangasinan, Philippines', 'harvest_date' => Carbon::now()->subDays(10)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(730)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Vegetable Seeds Mix', 'description' => 'High-quality vegetable seed mix including tomato, lettuce, and pepper varieties. High germination rate.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '200', 'unit' => 'packets', 'buy_now_price' => 45.00, 'location' => 'Manila, Philippines', 'harvest_date' => Carbon::now()->subDays(5)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Vermicompost', 'description' => 'Premium vermicompost produced by earthworms. Rich in nutrients and beneficial microorganisms.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '800', 'unit' => 'kg', 'starting_bid' => 32.00, 'current_bid' => 32.00, 'buy_now_price' => 48.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->subDays(8)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(730)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(2), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Pesticide (Organic)', 'description' => 'Organic pesticide made from natural ingredients. Safe for crops and environment.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '500', 'unit' => 'liters', 'buy_now_price' => 68.00, 'location' => 'Nueva Ecija, Philippines', 'harvest_date' => Carbon::now()->subDays(15)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1584256547471-fbc6e02a47d5?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Herbicide', 'description' => 'Effective herbicide for weed control. Safe when used as directed.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '400', 'unit' => 'liters', 'buy_now_price' => 55.00, 'location' => 'Isabela, Philippines', 'harvest_date' => Carbon::now()->subDays(12)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1574943439993-70d83eb7f90a?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Plant Growth Enhancer', 'description' => 'Natural plant growth promoter with vitamins and minerals. Increases yield and quality.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '300', 'unit' => 'liters', 'starting_bid' => 75.00, 'current_bid' => 75.00, 'buy_now_price' => 105.00, 'location' => 'Batangas, Philippines', 'harvest_date' => Carbon::now()->subDays(7)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => true, 'auction_start' => Carbon::now()->subHours(4), 'auction_end' => Carbon::now()->addDays(2), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1617478755490-e21232a5eeaf?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Soil Conditioner', 'description' => 'Improves soil structure and water retention. Perfect for clay and sandy soils.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '600', 'unit' => 'kg', 'buy_now_price' => 38.00, 'location' => 'Pangasinan, Philippines', 'harvest_date' => Carbon::now()->subDays(10)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(730)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1591857177730-94d77bfb8b6d?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Biochar', 'description' => 'Agricultural biochar for soil improvement. Increases nutrient retention and soil fertility.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '450', 'unit' => 'kg', 'buy_now_price' => 52.00, 'location' => 'Laguna, Philippines', 'harvest_date' => Carbon::now()->subDays(14)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(730)->format('Y-m-d'), 'organic_certified' => true, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Rice Straw Mulch', 'description' => 'Natural mulch from rice straw. Conserves moisture and suppresses weeds.', 'type' => 'produce', 'listing_type' => 'auction', 'quantity' => '700', 'unit' => 'kg', 'starting_bid' => 15.00, 'current_bid' => 15.00, 'buy_now_price' => 28.00, 'location' => 'Nueva Ecija, Philippines', 'harvest_date' => Carbon::now()->subDays(20)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(365)->format('Y-m-d'), 'organic_certified' => false, 'auction_start' => Carbon::now()->subHours(6), 'auction_end' => Carbon::now()->addDays(3), 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
            ['user_id' => $farmerId, 'category_id' => $categories['farm_inputs'] ?? 4, 'name' => 'Drip Irrigation Kit', 'description' => 'Complete drip irrigation system for efficient water use. Suitable for 1 hectare.', 'type' => 'produce', 'listing_type' => 'direct_buy', 'quantity' => '50', 'unit' => 'sets', 'buy_now_price' => 2850.00, 'location' => 'Manila, Philippines', 'harvest_date' => Carbon::now()->subDays(30)->format('Y-m-d'), 'expiry_date' => Carbon::now()->addDays(1825)->format('Y-m-d'), 'organic_certified' => false, 'status' => 'active', 'approval_status' => 'approved', 'image_url' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop&q=80', 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($listings as $listing) {
            $listingId = DB::table('listings')->insertGetId($listing);
            
            // Create stock batches for each listing
            DB::table('stock_batches')->insert([
                'listing_id' => $listingId,
                'batch_number' => 'BATCH-' . str_pad($listingId, 6, '0', STR_PAD_LEFT),
                'quantity' => intval($listing['quantity']),
                'remaining_quantity' => intval($listing['quantity']),
                'price' => $listing['buy_now_price'] ?? $listing['starting_bid'] ?? 0,
                'batch_date' => $listing['harvest_date'],
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
